import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={inter.className} >
        {/* <div className=" bg-cover bg-center min-h-screen" style={{ backgroundImage: "url('https://t4.ftcdn.net/jpg/02/09/89/51/360_F_209895174_j69ADCVlbY6xu9lgXyTicdTfcAOkSAU1.jpg')" }}> */}
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar/>
       <main className=" max-w-2xl  mx-auto"> {children}</main>
        </ThemeProvider></body>
    </html>
  );
}
